name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Docker Action
      uses: matootie/github-docker@v1.0.1
      with:
        username: neoncloth
        personalAccessToken: ${{ secrets.personalAccessToken }}
        imageName: master
        imageTag: latest
